### ISSUE TITLE
npm run build/yarn build fails to minify

### ISSUE THREAD

**Issue by arod2634** [smallwins/slack#96] opened 2017-11-16 06:08 UTC
I can't seem to get my create react app to compile using the default build script

$ yarn build
yarn build v0.21.3
react-scripts build
Creating an optimized production build...

Failed to compile.

Failed to minify the code from this file:

        ./node_modules/slack/src/_bind.js:10

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.

"Some third-party packages don't compile their code to ES5 before publishing to npm. This often causes problems in the ecosystem because neither browsers (except for most modern versions) nor some tools currently support all ES6 features. We recommend to publish code on npm as ES5 at least for a few more years."

So, how can this get fixed? Thanks for the help!

**Comment by danprince** [comment] 2017-11-16 12:27
Sounds like a duplicate of https://github.com/smallwins/slack/issues/90. There's a workaround in there.

@brianleroux Could add a buble/babel step to [scripts/browser-pkg](https://github.com/smallwins/slack/blob/master/scripts/browser-pkg) or just manually rewrite the ES6 code in the src?

**Comment by brianleroux** [comment] 2017-11-16 17:06
This *should* work I wonder what is causing the problem. It can't be the arrow fn here could it? https://github.com/smallwins/slack/blob/master/src/_bind.js#L10

**Comment by arod2634** [comment] 2017-11-17 01:42
I see. Thanks for the quick follow up.

> You could make a standalone build [1] and just include the script. (You'll need to modify that pkg command to export slack as a global.)

I'm trying to implement the recommended workaround by building and including the package separately, but I can't seem to get the 'pkg' command to work? 

`┌─[alexrodriguez][alexs-mbp-2][±][master {9} ✓][~/Sites/mailchimp-automation/node_modules/slack]
└─▪ sudo npm run pkg
Password:

> slack@9.0.9 pkg /Users/alexrodriguez/Sites/mailchimp-automation/node_modules/slack
> ./scripts/browser-pkg && jsmin -o slack.min.js slack.js && jsmin -o slack-testing.min.js slack-testing.js

sh: ./scripts/browser-pkg: No such file or directory`

What am I missing? How should I update the pkg command to export slack as a globaly?

**Comment by brianleroux** [comment] 2017-11-17 01:58
strange! clean build works on my machine (macOs). can you try these steps?

<img width="842" alt="screen shot 2017-11-16 at 5 57 14 pm" src="https://user-images.githubusercontent.com/990/32925637-c39ae04c-caf7-11e7-80db-bc35ef03cf7b.png">

**Comment by arod2634** [comment] 2017-11-17 02:40
Thanks @brianleroux. That worked when I tried the same command off of a fresh clone.

I built the pkg and moved the slack.min.js into the src/ folder of my app. 

I tried including it into one of my components, but it seems I'm still not including the script in a way that is going to work within the app. :(

`Failed to compile.

./src/components/mailchimp-automations/UploadToMailchimp.js
62:8-13 "export 'default' (imported as 'Slack') was not found in '../../helpers/slack.min.js'`

**Comment by brianleroux** [comment] 2017-11-17 04:16
just pushed a change [0] that exports the modules as `standalone` ---try a fresh clone and `npm run pkg` and lmk how it goes

[0] https://github.com/smallwins/slack/commit/095c849c822c3abc0d447cf685ac28405a6746c2

**Comment by brianleroux** [comment] 2017-11-18 00:39
Closing because I'm like 99.999% sure that fixed it but if you see any more issues don't hesitate to reopen/ask! Cheers 👍

**Comment by arod2634** [comment] 2017-11-19 23:41
Now I've got a new error when trying to include the standalone pkg build...

`Failed to compile.

./src/helpers/slack.min.js
  Line 1:  'define' is not defined   no-undef
  Line 1:  'define' is not defined   no-undef
  Line 1:  Unexpected use of 'self'  no-restricted-globals
  Line 1:  Unexpected use of 'self'  no-restricted-globals

Search for the keywords to learn more about each error.`

<img width="480" alt="screen shot 2017-11-19 at 5 39 16 pm" src="https://user-images.githubusercontent.com/632906/32997088-db4da494-cd50-11e7-872d-0461b863f919.png">

**Comment by brianleroux** [comment] 2017-11-20 06:02
Bummers! Can you create me repo that reproduces this fail ? 🕵🏻‍♂️

**Comment by brianleroux** [comment] 2017-11-21 20:20
Closing for duplicate #97 (and giving this another attempt rn!)

**Closed by brianleroux** 2017-11-21 20:20 UTC
